#!/usr/bin/env bash
# Writes inventory/hosts.autogen.yml from EC2_HOST_* in .env.
# Only includes hosts that have an IP set — supports EC2_INSTANCE_COUNT=1..4.
# Safe to call after provision (some hosts may still be blank).
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/_env.sh"
_load_ansible_env "$REPO_ROOT"

# At least one IP must be set to render a useful inventory.
_any_host_set=false
for v in EC2_HOST_SERVER1 EC2_HOST_SERVER2 EC2_HOST_SERVER3 EC2_HOST_CLIENT; do
  [ -n "${!v:-}" ] && _any_host_set=true && break
done

if ! $_any_host_set; then
  echo "WARN: No EC2_HOST_* values set in .env — inventory will be empty."
  echo "      Run: bash scripts/run_ec2_provision.sh  to create instances."
fi

OUT="${REPO_ROOT}/inventory/hosts.autogen.yml"

# Build the hosts block dynamically — only add entries that have an IP
_hosts_block=""
declare -A _host_map=(
  [EC2_HOST_SERVER1]=server1
  [EC2_HOST_SERVER2]=server2
  [EC2_HOST_SERVER3]=server3
  [EC2_HOST_CLIENT]=client
)
# Preserve insertion order (bash >=4.0)
_host_order=(EC2_HOST_SERVER1 EC2_HOST_SERVER2 EC2_HOST_SERVER3 EC2_HOST_CLIENT)

for v in "${_host_order[@]}"; do
  ip="${!v:-}"
  [ -z "$ip" ] && continue
  name="${_host_map[$v]}"
  _hosts_block+="        ${name}:\n          ansible_host: \"${ip}\"\n"
done

if [ -z "$_hosts_block" ]; then
  _hosts_block="        # no instances yet — run: bash scripts/run_ec2_provision.sh\n"
fi

cat > "$OUT" <<EOF
---
# Generated by scripts/render_inventory_from_env.sh — do not edit (gitignored).
# Re-generated automatically by ec2_provision.yml after launch.
all:
  children:
    linux:
      hosts:
$(printf '%b' "$_hosts_block")
      vars:
        ansible_user: ec2-user
        ansible_python_interpreter: auto_silent
EOF

echo "Wrote ${OUT}"
echo "Hosts included: $(grep -c 'ansible_host:' "$OUT" 2>/dev/null || echo 0)"
